### PR TITLE
README.md: Improve Markdown

### PR DESCRIPTION
**Pull request by perlun**
This makes it render with syntax highlighting, which makes it more readable.

(I would _like_ to fix the indentation also; 1-character tabs is far too little IMHO, 4 would make more sense. But, don't want to do that without discussing with you first, since I think you prefer it this way?)

### CODE REVIEW

**Comment by tomasbjerre** [comment]
Regarding indentation I just want to easily keep it in synk with the example usage. So I just use whatever I have there.

**Comment by perlun** [comment]
@tomasbjerre 

> Regarding indentation I just want to easily keep it in synk with the example usage. So I just use whatever I have there.

Fair enough. But would you be willing to change the `build.gradle` & example to use more spaces? (2 or 4 spaces.)

If not, it's fine; it's your software after all. :wink:

**Comment by tomasbjerre** [comment]
I think I value the text actually being visible without scrolling left and right. Paying the price of minimal indentation is fine if that means I dont have to scroll. I would have a different opinion if it was actual production code.

**Comment by perlun** [comment]
> I think I value the text actually being visible without scrolling left and right. Paying the price of minimal indentation is fine if that means I dont have to scroll.

Understandable, but the problem with minimal indentation is that the different levels are hard to distinguish from each other. That's my main concern with it. If you hate scrolling, I suggest going with 2 spaces per level - it's much easier to read than 1 space per indentation level.

**Comment by tomasbjerre** [comment]
It does not matter in this tiny example. Just a couple of indentation levels.

**Comment by perlun** [comment]
> It does not matter in this tiny example. Just a couple of indentation levels.

And I'm saying it _does_ matter. I find this example much harder to read, because of this specific reason. You are obviously free to disagree if you like, I'm just stating my opinion.

**Pull request merged**
